
# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18" # Specify Node.js version

# Environment variables
[build.environment]
  NODE_ENV = "production"
  # Ensure dev dependencies are installed during build
  NPM_FLAGS = "--include=dev"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
