
# Basic Netlify configuration for SPA
[build]
  command = "npm run build"
  publish = "dist"

# Redirects for SPA routing - essential for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers without overly restrictive CSP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
