
# Netlify configuration file for Apex Predator Insurance

[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_ENV = "production"
  # Ensure dev dependencies are installed during build
  NPM_FLAGS = "--include=dev"

# Redirects and rewrites for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Enable asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://lovable.dev https://images.unsplash.com; font-src 'self' data:; connect-src 'self' https://api.netlify.com;"
